server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  routes:
    user-service:
      path: /users/**
      url: http://user-service:8083
      strip-prefix: false

    order-service:
      path: /orders/**
      url: http://order-service:8082
      strip-prefix: false

  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  sensitive-headers: Cookie,Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
